project_id = "ccfuumvfuvnjlenvtvwn"

[functions.generate-image]
verify_jwt = true

[functions.manage-images]  
verify_jwt = true

[functions.manage-collections]
verify_jwt = true

[functions.save-generated-image]
verify_jwt = true

[functions.whatsapp-get-oauth-url]
verify_jwt = true

[functions.whatsapp-oauth-callback]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false